### ISSUE TITLE
Preserve ip-address when deploying to kubernetes

### ISSUE THREAD

**Issue by mikkel3000** [clickonetwo/tracker#1]
Due to the usage of kubernetes load-balancer service or ingresses the IP-addresses of the clients will not be correct in the timeseries data. 

Using `externalTrafficPolicy: Local` in the service is possible, but can be hard to achieve depending on how the nodes in the cluster are configured.

We would appreciate a feature which includes the values of the `X-Real-IP` and/or `X-Forwarded-For` headers in the timeseries. 
Configuring ingress-nginx to include these is quite easy.

An alternative would be the ability to configure a mapping of header values to fields in the timeseries data.

Thanks in advance, the process of deploying to kubernetes has been quite smooth so far.

**Comment by brotskydotcom2** [comment]
Thanks, for the feedback, @mikkelnygard! I agree completely that lack of this information is a problem.

In my experience, which header to use depends a lot on the number of proxied hops between the source machine and the adobe-usage-tracker receiver.  If there are no proxies between them, then both headers work well.  But if there are proxies between them, then the X-Forwarded-For header (as typically configured) is usually more reliable.

Because I expect each deployment team will know best which header they prefer, I will add configuration options in the Caddyfile to specify which header (if any) should be used to determine the source machine for the log, and I will also allow configuring which entry in the header to use (first or last) if there are multiple addresses (or multiple headers) provided.

**Comment by brotskydotcom2** [comment]
Hi @mikkelnygard and @thomasberglund, this is now fixed.  See the release notes for [the v1.1.0 release](https://github.com/clickonetwo/tracker/releases/tag/v1.1.0).  You can also get [a v1.1.0 image](https://hub.docker.com/repository/docker/clickonetwo/adobe_usage_tracker/general) from the Docker Hub; use `docker pull clickonetwo/adobe_usage_tracker:v1.1.0` to get it locally.
